name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload to Telegram
      run: |
        cd app/build/outputs/apk/debug/
        DEBUG_APK=$(echo *.apk)
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument" \
          -F chat_id="${{ secrets.TELEGRAM_TO }}" \
          -F document="@$DEBUG_APK" \
          -F caption="Equinox Kernel Adiutor"
        cd ../../../../../
